name: Spleef
version: 2.0.7
author: [Naruse, jeremaier]
main: fr.naruse.spleef.main.SpleefPlugin
softdepend: [DBAPI, Vault, HolographicDisplays]
commands:
  spleef:
    description: All commands for Spleef