name: Spleef
version: 2.1.1
author: [Naruse, jeremaier]
main: fr.naruse.spleef.main.SpleefPlugin
softdepend: [DBAPI, Vault, HolographicDisplays, PlaceholderAPI]
commands:
  spleef:
    description: All commands for Spleef