name: Spleef
version: 2.2.25
author: Naruse
main: fr.naruse.spleef.main.SpleefPlugin
softdepend: [DBAPI, Vault, HolographicDisplays, PlaceholderAPI, SecondThreadAPI, DecentHolograms, PlugManX]
commands:
  spleef:
    description: All commands for Spleef